// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFzW-wlTGv77LcCjg0sC4IRwXXZFzFMgk',
    appId: '1:621474644009:web:d41d9f1c15a9470b699c38',
    messagingSenderId: '621474644009',
    projectId: 'salah-app-2026',
    authDomain: 'salah-app-2026.firebaseapp.com',
    storageBucket: 'salah-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx2B1spj1MDbV42mjKQJRsOK6RYlSxbnU',
    appId: '1:621474644009:android:4d6fa1d5bf3b9697699c38',
    messagingSenderId: '621474644009',
    projectId: 'salah-app-2026',
    storageBucket: 'salah-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAflGelAldVwveaeTFQim0eqqWTqNsdxsg',
    appId: '1:621474644009:ios:27558fdd1102e571699c38',
    messagingSenderId: '621474644009',
    projectId: 'salah-app-2026',
    storageBucket: 'salah-app-2026.firebasestorage.app',
    iosClientId: '621474644009-ps1kfv8uu56r4u2k9qlbgkcbcc17nec2.apps.googleusercontent.com',
    iosBundleId: 'com.example.salah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAflGelAldVwveaeTFQim0eqqWTqNsdxsg',
    appId: '1:621474644009:ios:27558fdd1102e571699c38',
    messagingSenderId: '621474644009',
    projectId: 'salah-app-2026',
    storageBucket: 'salah-app-2026.firebasestorage.app',
    iosClientId: '621474644009-ps1kfv8uu56r4u2k9qlbgkcbcc17nec2.apps.googleusercontent.com',
    iosBundleId: 'com.example.salah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFzW-wlTGv77LcCjg0sC4IRwXXZFzFMgk',
    appId: '1:621474644009:web:5271808b56d29d5d699c38',
    messagingSenderId: '621474644009',
    projectId: 'salah-app-2026',
    authDomain: 'salah-app-2026.firebaseapp.com',
    storageBucket: 'salah-app-2026.firebasestorage.app',
  );
}
